spotmicro:

  # Load Joint controller publisher
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  # Load Joint controllers
  front_left_shoulder_position_controller:
    type: position_controllers/JointPositionController
    joint: front_left_shoulder

  front_left_foot_position_controller:
    type: position_controllers/JointPositionController
    joint: front_left_foot

  front_left_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: front_left_leg

  front_right_shoulder_position_controller:
    type: position_controllers/JointPositionController
    joint: front_right_shoulder

  front_right_foot_position_controller:
    type: position_controllers/JointPositionController
    joint: front_right_foot

  front_right_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: front_right_leg

  rear_left_shoulder_position_controller:
    type: position_controllers/JointPositionController
    joint: rear_left_shoulder

  rear_left_foot_position_controller:
    type: position_controllers/JointPositionController
    joint: rear_left_foot

  rear_left_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: rear_left_leg

  rear_right_shoulder_position_controller:
    type: position_controllers/JointPositionController
    joint: rear_right_shoulder

  rear_right_foot_position_controller:
    type: position_controllers/JointPositionController
    joint: rear_right_foot

  rear_right_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: rear_right_leg

  # PID values for our Joints
  # feel free to change them
  gazebo_ros_control/pid_gains:
    front_left_shoulder: {p: 100.0, i: 0.01, d: 10.0}
    front_left_leg: {p: 100.0, i: 0.01, d: 10.0}
    front_left_foot: {p: 100.0, i: 0.01, d: 10.0}
    front_right_shoulder: {p: 100.0, i: 0.01, d: 10.0}
    front_right_leg: {p: 100.0, i: 0.01, d: 10.0}
    front_right_foot: {p: 100.0, i: 0.01, d: 10.0}
    rear_left_shoulder: {p: 100.0, i: 0.01, d: 10.0}
    rear_left_leg: {p: 100.0, i: 0.01, d: 10.0}
    rear_left_foot: {p: 100.0, i: 0.01, d: 10.0}
    rear_right_shoulder: {p: 100.0, i: 0.01, d: 10.0}
    rear_right_leg: {p: 100.0, i: 0.01, d: 10.0}
    rear_right_foot: {p: 100.0, i: 0.01, d: 10.0}
